name: build 
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@v1.3.0
        id: scan
        with:
          image: centos:8.1.1911 
          format: yaml
          output: centos.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: tern 
          path: ${{ steps.scan.outputs.file }} 
      - uses: philips-labs/tern-action@v1.3.0
        id: scanspdx
        with:
          image: centos:8.1.1911 
          format: spdxtagvalue
          output: centos.spdx
      - uses: actions/upload-artifact@v2
        with:
          name: tern-spdx
          path: ${{ steps.scanspdx.outputs.file }} 
      - uses: philips-labs/tern-action@v1.3.0
        id: scanjson
        with:
          image: centos:8.1.1911 
          format: json
          output: centos.json
      - uses: actions/upload-artifact@v2
        with:
          name: tern-json
          path: ${{ steps.scanjson.outputs.file }} 
